version: '3.4'

services:

  rabbit:
    image: martin_rabbitmq_cluster_3.8.5:v1
    container_name: rabbit
    ports:
      - "5672:5672"
      - "9090:9090"
      - "15672:15672"
      - "61613:61613"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    restart: always

  martinperftest:
    image: pivotalrabbitmq/perf-test:latest
    command: "--uri amqp://admin:admin@rabbit:5672 -x 1 -y 10 -u 'throughput-test' -a --id 'test 1' -f persistent -q 5 --json-body --size 500 --rate 30000 --use-millis"
    volumes:
      - "./test.json:/test.json"
    depends_on:
      - rabbit
    links:
      - rabbit