version: '2'
services:
  web:
    image: httpd:2.4
    mem_limit: 256m
    networks:
      - default
      - internal
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluentd:
    build: ./fluentd
    mem_limit: 128m
    networks:
      - default
      - internal
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: elasticsearch:5.5
    mem_limit: 1536m
    networks:
      - default
      - internal
    expose:
      - 9200
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:5.5
    mem_limit: 128m
    networks:
      - default
      - internal
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

networks:
  internal:
    driver: bridge
