version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=aaaa1111
    networks:
      - app-tier
    ports:      
      - 6379:6379

  redis-slave:
    image: bitnami/redis:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=aaaa1111
      - REDIS_PASSWORD=aaaa1111
    ports:
      - 6380:6379
    depends_on:
      - redis
    networks:
      - app-tier

  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    environment:
      - REDIS_MASTER_PASSWORD=aaaa1111
    depends_on:
      - redis
      - redis-slave
    ports:
      - 26379:26379
    networks:
      - app-tier