version: '3.4'

services:

  rabbit:
    image: rabbitmq:3.13.3-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "9090:9090"
      - "15672:15672"
      - "61613:61613"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - "./rabbitmq/init_rabbit.sh:/init_rabbit.sh"
    restart: on-failure

  redis:
    image: redis:alpine3.20
    container_name: redis
    ports:
      - 6379:6379

  mariadb:
    image: mariadb:11
    container_name: mariadb
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - "./test_db:/test_db"
      - "./init_db.sh:/init_db.sh"        
  
  adminer:
    image: adminer:4-standalone
    container_name: adminer
    restart: always
    ports:
      - 9091:8080

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 7979:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
