
services:

  rabbit:
    image: nklee-rabbitmq:3.13.3-management
    container_name: rabbit
    ports:
      - "5672:5672" # AMQP 프로토콜 포트
      - "15672:15672" # RabbitMQ 관리 웹 UI
      - "61613:61613" # STOMP 프로토콜 포트
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - "./rabbitmq/init_rabbit.sh:/init_rabbit.sh"
    restart: on-failure

  janus:
    image: canyan/janus-gateway:master
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    container_name: janus
    depends_on:
      - rabbit
    links:
      - rabbit
    ports:
      - "8088:8088" # HTTP REST API 연동
      - "7088:7088" # HTTP Admin API 연동
      - "20000-20100:20000-20100/udp" # ICE 후보 포트
    volumes:
      - "./janus/config/janus.jcfg:/usr/local/etc/janus/janus.jcfg"
      - "./janus/config/janus.transport.http.jcfg:/usr/local/etc/janus/janus.transport.http.jcfg"
      - "./janus/config/janus.plugin.audiobridge.jcfg:/usr/local/etc/janus/janus.plugin.audiobridge.jcfg"
      - "./janus/config/janus.plugin.videoroom.jcfg:/usr/local/etc/janus/janus.plugin.videoroom.jcfg"
      - "./janus/config/janus.plugin.streaming.jcfg:/usr/local/etc/janus/janus.plugin.streaming.jcfg"
      - "./janus/config/janus.plugin.textroom.jcfg:/usr/local/etc/janus/janus.plugin.textroom.jcfg"
      - "./janus/config/janus.eventhandler.rabbitmqevh.jcfg:/usr/local/etc/janus/janus.eventhandler.rabbitmqevh.jcfg"
      - "./janus/janus.log:/var/log/janus.log"
    restart: on-failure