version: '3.4'

services:

  coturn:
    image: martin/coturn:4.6
    container_name: coturn
    networks:
      mynet:
        ipv4_address: 172.28.0.10
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49160-49200:49160-49200/udp"
    environment:
      - TURN_USER=test
      - TURN_PASSWORD=1234
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
    restart: on-failure

  nginx:
    image: nginx
    container_name: nginx
    networks:
      mynet:
        ipv4_address: 172.28.0.11
    ports:
      - 7979:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16