version: '3.4'

services:

  coturn1:
    image: martin/coturn:4.6
    container_name: coturn1
    networks:
      mynet:
        ipv4_address: 172.28.0.10
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "49160-49200:49160-49200/udp"
    environment:
      - TURN_USER=test
      - TURN_PASSWORD=1234
    volumes:
      - ./coturn1.conf:/etc/coturn/turnserver.conf
    restart: on-failure

  coturn2:
    image: martin/coturn:4.6
    container_name: coturn2
    networks:
      mynet:
        ipv4_address: 172.28.0.11
    ports:
      - "3479:3479"
      - "3479:3479/udp"
      - "5350:5350"
      - "5350:5350/udp"
      - "49260-49300:49260-49300/udp"
    environment:
      - TURN_USER=test
      - TURN_PASSWORD=1234
    volumes:
      - ./coturn2.conf:/etc/coturn/turnserver.conf
    restart: on-failure

  nginx:
    image: nginx
    container_name: nginx
    networks:
      mynet:
        ipv4_address: 172.28.0.12
    ports:
      - 7979:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16